### ISSUE TITLE
Nested reads support

### ISSUE THREAD

**Issue by avigoldman** [olivierwilkinson/prisma-nested-middleware#2]
Hey Olivier! 

Thanks for putting this package together.

Any thoughts on what it would take to support nested reads as well?

**Comment by olivierwilkinson** [comment]
Heya, no worries at all!

I'm not sure right now, although that's probably because I haven't had to write any middleware that would leverage it. Would you be able to describe what you have in mind? Or better yet provide an example of the middleware you are hoping to write?

**Comment by olivierwilkinson** [comment]
I've had a think about this and calling the passed middleware function for each nested include or select should be possible with the same strategy, is this what you were thinking?

**Comment by avigoldman** [comment]
Yes exactly!

**Comment by Tenrys** [comment]
I could use this as well!

**Comment by olivierwilkinson** [comment]
Ok, I'll see if I can get something together over the Christmas period!

**Comment by Tenrys** [comment]
Any news on this? I could try looking into it myself if necessary!

**Comment by olivierwilkinson** [comment]
@Tenrys heya,

I've made some progress on this but wanted to add a test suite first to avoid introducing regressions. I should be able to do that this weekend, if I don't manage I'll push my progress so you can have a look at it / finish it off 😄. Thanks for the offer!

**Comment by olivierwilkinson** [comment]
@Tenrys I've raised a draft PR which only has a few more things to do, I expect I'll be able to finish it off tomorrow! 😁

**Comment by olivierwilkinson** [comment]
> @Tenrys I've raised a draft PR which only has a few more things to do, I expect I'll be able to finish it off tomorrow! 😁
 
This is done! I've updated the README with some information as to what has changed, if anybody has any questions please feel free to comment here. I'm planning on doing some work on the documentation relatively soon so any questions will really help me figure out what to add.

Also, if the current strategy still doesn't work for someone's use case please comment here and I'll see what I can do 👍

**Comment by avigoldman** [comment]
Thanks so much for this!

**Comment by olivierwilkinson** [comment]
> Thanks so much for this!

No problem at all! 😁

I would hold off upgrading until [this fix PR](https://github.com/olivierwilkinson/prisma-nested-middleware/pull/7) is merged though 👍

**Comment by olivierwilkinson** [comment]
> I would hold off upgrading until [this fix PR](https://github.com/olivierwilkinson/prisma-nested-middleware/pull/7) is merged though 👍


The fix is merged! It should work as expected now 🤞
