### ISSUE TITLE
Thanks you very much!

### ISSUE THREAD

**Issue by xferqr** [olivierwilkinson/prisma-nested-middleware#21]
Thanks you very much!. I spent a week implementing nested middlewares, but still couldn't cover all their use cases. You saved everyone a many of nerve cells! 
p.s It is very strange that Prisma core team  did not implement this in 3 years.

**Comment by olivierwilkinson** [comment]
I'm glad you are finding it useful! Thanks for letting me know, this made my day! 🙌 

Please let me know if you have any feedback or find any issues 👍
