### ISSUE TITLE
Proposal to Transition from Middleware to Extension Due to Deprecation

### ISSUE THREAD

**Issue by iamfj** [olivierwilkinson/prisma-nested-middleware#29]
Hello @olivierwilkinson,

first thank you for the wonderful work on this project!

I recently came across updated documentation for Prisma indicating that middlewares are being deprecated and will soon be removed. Given this significant change, I wanted to inquire about the possibility of adapting prisma-nested-middleware to function as a Prisma extension.

https://www.prisma.io/docs/orm/prisma-client/client-extensions/middleware

From what I understand, transitioning to an extension might involve some modifications to the API, but I believe this approach could preserve the functionality and benefits of the current middleware setup. Could you please consider this transition? I think many users of prisma-nested-middleware would benefit from maintaining its capabilities in the context of the evolving Prisma ecosystem.

Looking forward to your thoughts on this proposal. 🚀

**Comment by olivierwilkinson** [comment]
Hi there,

Thank you for your kind words!

I have actually ported this library to extensions already, you can find the repo here: [olivierwilkinson/prisma-extension-nested-operations](https://github.com/olivierwilkinson/prisma-extension-nested-operations)

I hope you find it useful! 😄

**Comment by iamfj** [comment]
Thanks!
