### ISSUE TITLE
v1.1.0 returns breaking values for empty relationships on models

### ISSUE THREAD

**Issue by Tenrys** [olivierwilkinson/prisma-nested-middleware#6]
Hey, haven't had the time to test the new update in a more practical sense, however I did update it on my project as I still had it running with a pass-through middleware, and noticed that it created errors with https://github.com/maoosi/prisma-appsync when trying to list models, querying their relationships, and getting results where the relationship was empty.

Here is a short example of the behavior difference:

With this schema:

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
  // previewFeatures = ["clientExtensions"]
}

generator appsync {
  provider = "prisma-appsync"
}

model User {
  uuid      String   @id @default(uuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  name String

  post Post?
}

model Post {
  uuid      String   @id @default(uuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  content String

  userUuid String @unique
  user     User   @relation(fields: [userUuid], references: [uuid])
}
```

After adding some data, run this example code:

```ts
import { PrismaClient } from "@prisma/client";
import { createNestedMiddleware } from "prisma-nested-middleware";

const prisma = new PrismaClient();

(async () => {
	console.log("Pre Nested Middleware");
	console.log(
		await prisma.user.findMany({
			select: {
				uuid: true,
				name: true,
				post: {
					select: {
						uuid: true,
						content: true,
					},
				},
			},
		})
	);

	console.log("Adding Nested Middleware");
	prisma.$use(
		createNestedMiddleware(async (params, next) => {
			return await next(params);
		})
	);

	console.log("Post Nested Middleware");
	console.log(
		await prisma.user.findMany({
			select: {
				uuid: true,
				name: true,
				post: {
					select: {
						uuid: true,
						content: true,
					},
				},
			},
		})
	);
})();
```

Output: 
![image](https://user-images.githubusercontent.com/3979239/211854234-30385911-3a10-45a7-9000-01e0d31dd25b.png)

As you can see, `post` becomes an empty object if it can't find a relationship, instead of `null`, which causes issues with a GraphQL API, which will see fields of that relationship as `null` when they are not meant to be.

**Comment by olivierwilkinson** [comment]
Thanks for letting me know! I'll look into it today, hopefully it's only a minor mistake and I can get a fix out quickly.

**Comment by olivierwilkinson** [comment]
@Tenrys I've got a fix PR up. 😄 

I've published the fix to the `next` channel for you to try: you should be able to install it with `prisma-nested-middleware@next`. Let me know if it fixes the problem for you!

**Comment by Tenrys** [comment]
That same script seems to work better, yup!

**Comment by olivierwilkinson** [comment]
> That same script seems to work better, yup!

Great! Thanks for checking so quickly 😄
